 name: Test Manual

 on:
   workflow_dispatch:

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Get Your Code
         uses: actions/checkout@v4

       - name: Say Hello to the World
         run: echo "Hello, World!"